//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiliveryApp2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveries
    {
        public int delivery_id { get; set; }
        public int order_id { get; set; }
        public int courier_id { get; set; }
        public string delivery_status { get; set; }
        public System.DateTime delivery_date { get; set; }
    
        public virtual couriers couriers { get; set; }
        public virtual orders orders { get; set; }
    }
}
