//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiliveryApp2._0.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dilivery2DBEntities : DbContext
    {
        public Dilivery2DBEntities()
            : base("name=Dilivery2DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<couriers> couriers { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<deliveries> deliveries { get; set; }
        public virtual DbSet<menu_items> menu_items { get; set; }
        public virtual DbSet<order_items> order_items { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<restaurants> restaurants { get; set; }
        public virtual DbSet<reviews> reviews { get; set; }
    }
}
