//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiliveryApp2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menu_items()
        {
            this.order_items = new HashSet<order_items>();
        }
    
        public int menu_item_id { get; set; }
        public int restaurant_id { get; set; }
        public string item_name { get; set; }
        public string item_description { get; set; }
        public decimal item_price { get; set; }
    
        public virtual restaurants restaurants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
    }
}
