//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiliveryApp2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int review_id { get; set; }
        public int restaurant_id { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
        public System.DateTime review_date { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual restaurants restaurants { get; set; }
    }
}
